import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import java.util.jar.Attributes

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.shadow)
    alias(libs.plugins.release)

    alias(libs.plugins.paper)
    alias(libs.plugins.paper.convention)
    alias(libs.plugins.paper.run)
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

version = scmVersion.version

dependencies {
    implementation(libs.metrics)

    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    paperweight.paperDevBundle("1.21.8-R0.1-SNAPSHOT")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<AbstractArchiveTask>().configureEach {
    isPreserveFileTimestamps = false
    isReproducibleFileOrder = true

    from("LICENSE")
    from("README.md")
    from("assets/text/licenses") {
        into("licenses")
    }

    filePermissions {
        user.read = true
        user.write = true
        user.execute = false

        group.read = true
        group.write = false
        group.execute = false

        other.read = true
        other.write = false
        other.execute = false
    }

    dirPermissions {
        user.read = true
        user.write = true
        user.execute = true

        group.read = true
        group.write = false
        group.execute = true

        other.read = false
        other.write = false
        other.execute = true
    }
}

tasks.withType<ShadowJar>().configureEach {
    minimize()

    enableAutoRelocation = true
    relocationPrefix = "dev.enderman.unboat.dependencies"
}

sourceSets.main {
    resourceFactory {
        paperPluginYaml {
            name = "Unboat"
            description = "A Minecraft Paper plugin that prevents aggravated mobs from getting stuck in boats"

            main = "dev.enderman.unboat.Unboat"
            apiVersion = "1.21.8"
            version = project.version.toString()

            authors.add(
                "Esoteric Enderman"
            )

            website = "https://gitlab.com/esotericenderman/unboat"
        }
    }
}
