/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.enderman.unboat

import org.bukkit.plugin.java.JavaPlugin

@Suppress("unused")
class Unboat : JavaPlugin() {
    override fun onEnable() {
        server.pluginManager.registerEvents(BoatListener(), this)
        server.pluginManager.registerEvents(AggravateListener(), this)
    }
}
